name: MLflow CI Training & Docker

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Tambahkan 'docker' agar mlflow bisa build image
          pip install mlflow scikit-learn pandas joblib dagshub docker 

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Arahkan ke DagsHub agar tidak tersimpan lokal saja
          export MLFLOW_TRACKING_URI="https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/insurance_danu.mlflow"
          mlflow run MLProject --env-manager=local

      - name: Get latest MLflow run_id
        id: get_id
        run: |
          # Perbaikan: Cek folder sebelum ambil ID untuk cegah Exit 1
          if [ -d "mlruns/0" ]; then
            RUN_ID=$(ls -td mlruns/0/*/ | grep -Eo '[0-9a-f]{32}' | head -n 1)
            echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
            echo "Latest run_id found: $RUN_ID"
          else
            echo "Error: Folder mlruns/0 tidak ditemukan. Training gagal."
            exit 1
          fi

      - name: Build Docker Model
        run: |
          # Membungkus model menjadi image Docker siap saji
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/model" \
            --name insurance_danu_model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag insurance_danu_model ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest

      - name: Commit & Push MLflow Artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/
          git commit -m "Add MLflow artifacts [skip ci]" || echo "No changes"
          git push origin main
