name: CI Workflow

on:
  push:
    branches: ["main"]

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub scikit-learn pandas numpy matplotlib docker

    - name: Run mlflow project
      run: |
        # KUNCI PERBAIKAN: 
        # Kita mengarahkan ke direktori ./MLProject agar MLflow mencari file 'MLProject' di dalamnya.
        # Ini akan menghilangkan error IsADirectoryError.
        mlflow run ./MLProject --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        # MLflow membuat folder mlruns di tempat perintah dijalankan.
        # Karena kita menjalankan dari root, folder mlruns ada di mlruns/
        RUN_ID=$(find mlruns/0 -maxdepth 1 -type d -printf '%P\n' | grep -E '^[0-9a-f]{32}$' | head -n 1)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    - name: Commit & Push mlruns
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # Menambahkan folder mlruns yang otomatis muncul setelah mlflow run berhasil
        git add mlruns/
        git commit -m "Upload mlruns results [skip ci]" || echo "No changes to commit"
        git push origin main

    - name: Build Docker Model
      if: env.RUN_ID != ''
      run: |
        mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "smokehealth_model" 

    - name: Log in to Docker Hub
      if: env.RUN_ID != ''
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag and Push Docker Image
      if: env.RUN_ID != ''
      run: |
        docker tag smokehealth_model ${{ secrets.DOCKER_HUB_USERNAME }}/smokehealth_model:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/smokehealth_model:latest
