name: MLflow CI Training & Docker

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas joblib dagshub docker 

      - name: Run MLflow Project
        env:
          # Pastikan nama secret di GitHub Settings sama persis dengan di bawah ini
          D_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Set URI Tracking DagsHub sesuai gambar (insurance_danu)
          export MLFLOW_TRACKING_URI="https://dagshub.com/danusisda05-ai/insurance_danu.mlflow"
          export MLFLOW_TRACKING_USERNAME="danusisda05-ai"
          export MLFLOW_TRACKING_PASSWORD="$D_TOKEN"
          
          # Autentikasi paksa agar tidak Error 403
          python -c "import dagshub; dagshub.auth.add_app_token('$D_TOKEN')"
          
          # Jalankan training
          mlflow run MLProject --env-manager=local

      - name: Get latest MLflow run_id
        id: get_id
        run: |
          if [ -d "mlruns/0" ]; then
            RUN_ID=$(ls -td mlruns/0/*/ | grep -Eo '[0-9a-f]{32}' | head -n 1)
            echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          else
            echo "Folder mlruns/0 tidak ditemukan!"
            exit 1
          fi

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/model" \
            --name insurance_danu_model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag insurance_danu_model ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest
