name: MLflow CI Training & Docker

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas joblib dagshub docker 

      - name: Run MLflow Project
        env:
          D_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          export MLFLOW_TRACKING_URI="https://dagshub.com/danusisda05-ai/insurance_danu.mlflow"
          export MLFLOW_TRACKING_USERNAME="danusisda05-ai"
          export MLFLOW_TRACKING_PASSWORD="$D_TOKEN"
          
          python -c "import dagshub; dagshub.auth.add_app_token('$D_TOKEN')"
          
          # Jalankan training
          mlflow run MLProject --env-manager=local | tee run_output.txt
          
          # Ambil RUN_ID
          RUN_ID=$(grep -oE "[0-9a-f]{32}" run_output.txt | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          
          echo "Menunggu sinkronisasi DagsHub..."
          sleep 15

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/danusisda05-ai/insurance_danu.mlflow"
          MLFLOW_TRACKING_USERNAME: "danusisda05-ai"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # 1. Cek isi artifact untuk memastikan path-nya
          echo "Mengecek isi artifact di DagsHub..."
          mlflow artifacts list --run-id ${{ env.RUN_ID }} > artifacts_list.txt
          cat artifacts_list.txt

          # 2. Download seluruh isi artifact ke folder lokal
          # Jika folder 'model' tidak ada, kita ambil root-nya
          mlflow artifacts download --run-id ${{ env.RUN_ID }} --dst-path ./all_artifacts
          
          # 3. Cari di mana file 'MLmodel' berada secara otomatis
          MODEL_PATH=$(find ./all_artifacts -name "MLmodel" -exec dirname {} \;)
          echo "Model ditemukan di: $MODEL_PATH"

          # 4. Build Docker dari path yang ditemukan secara otomatis
          mlflow models build-docker \
            --model-uri "$MODEL_PATH" \
            --name insurance_danu_model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag insurance_danu_model ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest
