name: MLflow CI Training & Docker

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas joblib dagshub docker 

      - name: Run MLflow Project
        env:
          D_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          export MLFLOW_TRACKING_URI="https://dagshub.com/danusisda05-ai/insurance_danu.mlflow"
          export MLFLOW_TRACKING_USERNAME="danusisda05-ai"
          export MLFLOW_TRACKING_PASSWORD="$D_TOKEN"
          
          # Login Dagshub
          python -c "import dagshub; dagshub.auth.add_app_token('$D_TOKEN')"
          
          # Jalankan training
          mlflow run MLProject --env-manager=local | tee run_output.txt
          
          # Ambil RUN_ID
          RUN_ID=$(grep -oE "[0-9a-f]{32}" run_output.txt | head -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          
          # DEBUG: Cek folder apa saja yang ada di DagsHub untuk Run ID ini
          echo "Daftar folder di DagsHub untuk ID $RUN_ID:"
          mlflow artifacts list --run-id $RUN_ID

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/danusisda05-ai/insurance_danu.mlflow"
          MLFLOW_TRACKING_USERNAME: "danusisda05-ai"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Gunakan RUN_ID yang sudah didapat
          # Kita gunakan path 'model' (biasanya default MLflow)
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/model" \
            --name insurance_danu_model

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag insurance_danu_model ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest
